# services:
#   aji-db:
#     image: mysql:latest
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: your_root_password
#       MYSQL_DATABASE: aji-db
#       MYSQL_USER: aji-user
#       MYSQL_PASSWORD: your_password
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - "3306:3306"

#   phpmyadmin:
#     platform: linux/arm64/v8
#     image: phpmyadmin:latest
#     restart: unless-stopped
#     depends_on:
#       - aji-db
#     environment:
#       PMA_HOST: aji-db
#       MYSQL_ROOT_PASSWORD: your_root_password
#     ports:
#       - "8888:80"

# volumes:
#   db_data:

services:
  aji-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # - PORT=3000
      - DATABASE_HOST=aji-db
      - DATABASE_PORT=3306
      - DATABASE_USER=aji-user
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=aji-db
      - TYPEORM_SYNC=true
    depends_on:
      - aji-db
    ports:
      - "3000:3000"

  aji-db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: aji-db
      MYSQL_USER: aji-user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    platform: linux/arm64/v8
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - aji-db
    environment:
      PMA_HOST: aji-db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8888:80"

volumes:
  db_data: